name: Update GitHub README Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run JavaScript automation
        run: |
          node scripts/github_stats.js
